name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sett opp Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Bygg prosjektet med Maven og kjør tester
      - name: Build with Maven
        run: mvn clean install

      # Eventuelt: kjør spesifikke tester
      - name: Run Unit Tests
        run: mvn test
